//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/29
//  @ Author : wufengan
//
//


#include "StaticData.h"

void StaticData::StaticData() {

}

StaticData StaticData::sharedStaticData() {

}

void StaticData::purge() {

}

int StaticData::intyValueForKey(std::string key) {

}

int StaticData::stringValueFromKey(std::string key) {

}

float StaticData::floatValueFromKey(std::string key) {

}

bool StaticData::booleanFromKey(std::string key) {

}

cocos2d::CCPoint StaticData::pointFromKey(std::string key) {

}

cocos2d::CCRect StaticData::rectFromKey(std::string key) {

}

cocos2d::CCSize StaticData::sizeFromKey(std::string key) {

}

bool StaticData::init() {

}

StaticData::StaticData() {

}
